spring.application.name=demo


# --- Valkey connection (adjust if not localhost) ---
spring.data.Valkey.host=localhost
spring.data.Valkey.port=6379
spring.valkey.database=0
# spring.data.Valkey.password=yourPasswordIfAny

# --- Actuator / metrics / Prometheus ---
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
