receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

connectors:
  spanmetrics:
    histogram:
      explicit:

processors:
  batch: {}

exporters:
  # ---- AWS BACKENDS ----
  awsxray:
    region: "us-east-1"

  awsemf:
    region: "us-east-1"
    log_group_name: "/aws/otel/traces"
    namespace: "opentelemtey_tests"
    dimension_rollup_option: "NoDimensionRollup"

  # ---- LOCAL DEBUGGING ----
  otlphttp/jaeger:
    endpoint: http://jaeger:4318
    tls:
      insecure: true

  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: "debug"

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - awsxray
        - otlphttp/jaeger
        - spanmetrics
        - debug

    metrics:
      receivers: [spanmetrics, otlp]
      processors: [batch]
      exporters:
        - awsemf
        - debug
